### ISSUE TITLE
Most recent doesn't seem to be updating

### ISSUE THREAD

**Issue by danpie-cw** [lekjos/dailygroove#63]
**Describe the bug**
After a win, the winner displays in bottom section, but the upper section hasn't shown a recent win in a while. 

**To Reproduce**
1. Declare a winner for some one who already has a win
2. The winners "most recent" win date isn't updated

**Expected behavior**
Expected that when a person is declared the winner, their "most recent win" would show todays date

**Screenshots**
![image](https://github.com/lekjos/dailygroove/assets/96074519/b4146e33-5874-4acc-9b93-0e159594c350)
![image](https://github.com/lekjos/dailygroove/assets/96074519/d5f89f4b-65fb-4852-8170-4fbefb7dac8c)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge
 - Version 119.0.2151.44 (Official build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lekjos** [comment]
Thanks Dan! I’ll take a look this weekend On Fri, Nov 10, 2023 at 07:03, danpie-cw ***@***.***> wrote:  
Describe the bug
After a win, the winner displays in bottom section, but the upper section hasn't shown a recent win in a while.
To Reproduce
Steps to reproduce the behavior:

Declare a winner for some one who already has a win
The winners "most recent" win date isn't updated

Expected behavior
Expected that when a person is declared the winner, their "most recent win" would show todays date
Screenshots
If applicable, add screenshots to help explain your problem.


Desktop (please complete the following information):

OS: Windows 11
Browser Edge
Version 119.0.2151.44 (Official build) (64-bit)

Smartphone (please complete the following information):

Device: [e.g. iPhone6]
OS: [e.g. iOS8.1]
Browser [e.g. stock browser, safari]
Version [e.g. 22]

Additional context
Add any other context about the problem here.

**Comment by lekjos** [comment]
Thanks @danpie-cw! I'll take a look this weekend

**Comment by lekjos** [comment]
fixed and deployed via https://github.com/lekjos/dailygroove/commit/e390d060c34179ba418c33cd57e0688344aae3b1
